name: click
description: Vibes n insha'allah.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  path_parsing: ^0.1.3
  touchable: ^0.2.0
  xml: ^4.1.0

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - images/ng.svg
